### ISSUE TITLE
gather dataframe

### ISSUE THREAD

**Issue by mcgregorv** [mareframe/vat#12]
When I ran it, create_vadt fell over unless I made everything 'gather' was to be used on a data.frame

**Comment by cddesja** [comment]
Can you share your model via Dropbox so I can take a peak?

**Comment by cddesja** [comment]
Are you getting a message that says "Error: unknown column 'X1'"?

**Comment by mcgregorv** [comment]
Hi Chris

Yes, I’ve put it here
ftp://ftp.niwa.co.nz/os2020/ATLANTIS/TBGB_SendToChris

if you need a password it will be mcgregorv
Let me know if you have any trouble getting it. It should have everything you need in it, including the Atlantis.exe and the output files. Also my R script and my version of your create_vadt.R

It’s nice to finally be using your shiny ap – it’s very good! Thanks ☺

And yes, it was Error: unknown column 'X1'  which lead me to defining the object as a data.frame

Vidette

**Comment by mcgregorv** [comment]
yes

**Comment by mcgregorv** [comment]
Also, I see in the diets you’ve left the consumed units undefined. If the prey species is a vertebrate, Atlantis has output the amount consumed as individuals per second and if it is an invert it is mg N per second (at least I’m mostly sure that’s right!)

**Comment by cddesja** [comment]
Thanks. I see what you're referring to about the `data.frame()` command. Regarding diets, are you referring to the diets table or a diet plot or the Markdown file (the starting page)? I don't need your model.

**Comment by mcgregorv** [comment]
The Diet Data plots, which seem to be using the OutputDietCheck.txt data

**Comment by cddesja** [comment]
OK. I'll take a look at this. Looks like either `dplyr` or `tidyr` is responsible for this bug. Thanks for fixing it for me.

**Comment by cddesja** [comment]
This has now been fixed in the mat-age-fix branch. If you want to test it, which Matteo has, you can do the following.

```r
devtools::install_github(repo="mareframe/vat", ref = "mat-age-fix")
```

Regarding the y-axis label, I don't know what's the most elegant option. I could have a long y-axis label, but seems not so nice either. @mcgregorv, do you have a specific suggestion?

**Comment by mcgregorv** [comment]
Hey Chris
Sorry, the units for diet check are just proportions. For a given predator/cohort, it gives the proportion of diet made up by each of the prey species over the given year. So the y-axis should be ‘Proportion of predator diet’ or something like that.
Cheers,
Vidette
